### ISSUE TITLE
[Idea]: migrate stdlib to use ESLint for linting TypeScript files

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/google-summer-of-code#12]
### Idea

Currently, stdlib uses tslint to lint TypeScript files; however, this utility is now deprecated. The goal of this idea is to migrate stdlib away from tslint to use ESLint for linting. We already use ESLint for linting JavaScript, and being able to use the same linter for TypeScript files would be a significant development improvement, given stdlib's investment in developing custom ESLint rules for enforcing project conventions.

### Expected Outcomes

Linting of stdlib's TypeScript files will be performed by ESLint.

### Involved Software

No other software is necessary.

### Prerequisite Knowledge

JavaScript, Node.js.

### Difficulty

Beginner/Intermediate. 

### Project Length

175/350 hours. Can be scoped accordingly. Scope can be expanded to create custom ESLint rules to enforce particular aspects of stdlib conventions.

**Comment by kgryte** [comment]
@Planeshifter Should we close this idea? While some work remains to be done, I don't think it is enough to support a GSoC project. What are your thoughts?

**Comment by Planeshifter** [comment]
@kgryte Agreed, I think we should close this one out. While there are many incremental improvements to be made, I think these can happen over time and don't need the concentrated effort of a GSoC project.
